# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
r_check_args: --as-cran
r_build_args: --compact-vignettes=both

r:
  - release
  - devel

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
  - r: devel

before_install:
  - export DISPLAY=:99.0

apt_packages:
  - libgl1-mesa-dev
  - libglu1-mesa-dev
  - ghostscript
  - qpdf

services:
  - xvfb

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'


before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
